// ===========================================================================
//  warnings_off.inc - Globalno iskljucivanje svih warninga
//  Ukljuciti na pocetku gamemoda: #include <warnings_off>
// ===========================================================================

#if defined _INC_warnings_off
    #endinput
#endif
#define _INC_warnings_off

#pragma warning disable 202
#pragma warning disable 203
#pragma warning disable 204
#pragma warning disable 209
#pragma warning disable 213
#pragma warning disable 214
#pragma warning disable 217
#pragma warning disable 219
#pragma warning disable 231
#pragma warning disable 239
#pragma warning disable 240
#pragma warning disable 247
#pragma warning disable 252
