// Inventory Constants
#if !defined MAX_INV_SLOTS
	#define MAX_INV_SLOTS (30)
#endif

// Item Categories
#define INV_CAT_SPECIAL (0)
#define INV_CAT_FOOD (1)
#define INV_CAT_TOOL (2)
#define INV_CAT_WEAPON (3)
#define INV_CAT_MATERIAL (4)
#define INV_CAT_ARMOR (5)

// Item Icons
#define ICON_INGREDIENT (0)
#define ICON_PIZZA (1)
#define ICON_HAMBURGER (2)
#define ICON_CHICKEN (3)
#define ICON_JUICE (4)
#define ICON_BEER (5)
#define ICON_SCREWDRIVER (6)
#define ICON_CROWBAR (7)
#define ICON_HAMMER (8)
#define ICON_FUELCAN (9)
#define ICON_DYNAMITE (10)
#define ICON_LAPTOP (11)
#define ICON_METAL (12)
#define ICON_SCRAP (13)
#define ICON_IRON (14)
#define ICON_PLASTIC (15)
#define ICON_MASK (16)
#define ICON_CAMPFIRE (17)
#define ICON_BRASS_KNUCKLES (18)
#define ICON_PISTOL (19)
#define ICON_SHOTGUN (20)
#define ICON_RIFLE (21)
#define ICON_EXPLOSIVE (22)
#define ICON_MELEE (23)
